### ISSUE TITLE
Problems about SentenceTransformer

### ISSUE THREAD

**Issue by yanyou426** [sem2vec/sem2vec-SE#1]
Hello, when I run `bash ./scripts/coreutils_nx_graphs_batch.sh`
I got a problem with `No module named 'sentence_transformers'`
Then I just install it with `pip`
This time the bug occurs as:
```
Traceback (most recent call last):
  File "./build_nx_graphs.py", line 3, in <module>
    from nx_graphs.prepare_data import dump_bin_tracelets_graphs, dump_bin_tracelets_inlined_graphs
  File "/home2/kyhe/workspace/sem2vec-SE/nx_graphs/prepare_data.py", line 13, in <module>
    from bert.encoding_formulas import tracelet_to_encoding
  File "/home2/kyhe/workspace/sem2vec-SE/bert/encoding_formulas.py", line 18, in <module>
    model = SentenceTransformer("./bert/FoBERT2-SS")
  File "/home2/kyhe/anaconda3/envs/sem2vec/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 77, in __init__
    raise ValueError("Path {} not found".format(model_name_or_path))
ValueError: Path ./bert/FoBERT2-SS not found
```
Did I install the wrong version of 'sentence_transformers'?

**Comment by whj0401** [comment]
You need to train the model and put it in the folder `./bert/FoBERT2-SS` first...
